### ISSUE TITLE
Closing the connection fails when consumer was destroyed

### ISSUE THREAD

**Issue by adaxi** [memphisdev/memphis.js#186]
**Bug description**
When attempting to close the connection after a consumer was destroyed, the following exception is thrown:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

memphis: 409 consumer deleted
    at checkJsErrorCode (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/jsutil.js:93:20)
    at checkJsError (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/jsutil.js:76:12)
    at SubscriptionImpl.callback (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/jsclient.js:168:53)
    at ProtocolHandler.processMsg (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/protocol.js:330:17)
    at ProtocolHandler.push (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/protocol.js:420:22)
    at Parser.parse (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/parser.js:197:41)
    at ProtocolHandler.<anonymous> (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/protocol.js:189:45)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gbo/Workspaces/@escaux/message-broker/node_modules/nats/lib/nats-base-client/protocol.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event at:
    at fetchAndHandleMessages (/home/gbo/Workspaces/@escaux/message-broker/node_modules/memphis-dev/lib/consumer.js:63:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'MemphisError',
  code: '409',
  chainedError: undefined
```

**To Reproduce**

Use the following script to reproduce the issue:
```js
import { memphis } from 'memphis-dev'


const test = async () => {
  const memphisConnection = await memphis.connect({
    host: 'localhost',
    port: 6666,
    username: 'root',
    password: 'memphis'
  })

  const consumer = await memphisConnection.consumer({
    consumerName: 'DefaultConsumer',
    consumerGroup: 'DefaultConsumerGroup',
    stationName: 'test.topic'
  })

  consumer.on('message', () => {
    console.log('got a message')
  })

  await consumer.destroy()

  await memphisConnection.close()
}

test()
```

**Expected behavior**
I expected to be able to close my connection without any exceptions.

**Additional context**
The issue does not seem to occur if we omit the `await consumer.on('message', () => {})` function call.

I am using image: `memphisos/memphis:1.2.0` and SDK v1.1.2

**Comment by yanivbh1** [comment]
Hey @adaxi ,
Thanks for raising it up.
Adding @shay23b and @shohamroditimemphis

**Comment by shohamroditimemphis** [comment]
Hi @adaxi , I will take a look and notify ASAP

**Comment by idanasulinmemphis** [comment]
Will be fixed on version 1.2.0

**Comment by adaxi** [comment]
@yanivbh1, @idanasulinmemphis,

I can still reproduce this with: memphisos/memphis:1.4.0 and SDK v1.2.4, I have exactly the same output has described in my initial description.

Should I open a new ticket?

**Comment by idanasulinmemphis** [comment]
Hi @adaxi we will check it out. 
In the meantime if you want to solve it faster, would you like to try fix this on your own and open a PR?

**Comment by madestreel** [comment]
@idanasulinmemphis Had a bit a look at the nats server to understand why the SDK gets the 409.

If I understood correctly this "409 Consumer Deleted" was introduced because previously the only way for the client to know that a consumer / producer was removed was by relying on the heartbeat which introduce some delay (see this [issue](https://github.com/nats-io/nats-server/issues/3603)).

I suppose that it is up to the client to delete the consumer/producer locally in case such an error occurs instead of throwing it to the application (client being the memphis SDK and application being the application using the memphis SDK).

Is this something you agree with, or any other suggestions on how this should be handled?

**Comment by madestreel** [comment]
@idanasulinmemphis I think this one should be re-opened
