### ISSUE TITLE
Bun Driver Error

### ISSUE THREAD

**Issue by oxa0** [memphisdev/memphis.js#262]
**Describe the bug**
i get this error on bun runtime

**To Reproduce**
1. Bun -v 1.0.33
2. memphis-dev 1.3.2

error: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)

656 |             const data = this.JSONC.encode(createProducerReq);
657 |             let createRes = await this.request('$memphis_producer_creations', data, timeoutRetry, { timeout: 20000 });
658 |             createRes = this.JSONC.decode(createRes.data);
659 |             if (createRes.error != '') {
660 |                 throw (0, utils_1.MemphisError)(new Error(createRes.error));
661 |             }
                                                      ^
error: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)
      at /home/endri/tb/node_modules/memphis-dev/lib/memphis.js:661:49
656 |             const data = this.JSONC.encode(createProducerReq);
657 |             let createRes = await this.request('$memphis_producer_creations', data, timeoutRetry, { timeout: 20000 });
658 |             createRes = this.JSONC.decode(createRes.data);
659 |             if (createRes.error != '') {
660 |                 throw (0, utils_1.MemphisError)(new Error(createRes.error));
661 |             }
                                                      ^
error: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)
      at /home/endri/tb/node_modules/memphis-dev/lib/memphis.js:661:49

**Comment by oxa0** [comment]
745 |                     partitions = createRes.partitions_update.partitions_list;
746 |                 }
747 |             }
748 |             catch (_b) {
749 |                 const errMsg = createRes.data ? createRes.data.toString() : createRes.error.toString();
750 |                 if (errMsg != '') {
                                                                          ^
error: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)
      at /home/endri/tb/node_modules/memphis-dev/lib/memphis.js:750:69
745 |                     partitions = createRes.partitions_update.partitions_list;
746 |                 }
747 |             }
748 |             catch (_b) {
749 |                 const errMsg = createRes.data ? createRes.data.toString() : createRes.error.toString();
750 |                 if (errMsg != '') {
                                                                          ^
error: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)
      at /home/endri/tb/node_modules/memphis-dev/lib/memphis.js:750:69
